homeapp/urls.py
from django.urls import path
from . import views
# from productapp.views import ProductDetailView

app_name='homeapp'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('cat/<int:pk>/', views.category_filter, name='categorypage'),
    path('product/', views.product, name='product_page'),
    path('product/<int:pk>/', views.product_details, name='product_detailspage'),
    path('career/', views.career, name='career_page'),
    path('who_we_are/', views.who_we_are, name='who_we_are_page'),
    path('who_we_are_for/', views.who_we_are_for, name='who_we_are_for_page'),  
    
]

homeapp/models.py
from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.html import mark_safe
from django.conf import settings
from numpy import product

# Create your models here. 
class Consultancy(models.Model): 
    title = models.CharField(max_length=255,help_text='title must be in 255 character')
    icon =models.FileField(upload_to="consultancy_imgs",null=True,blank=True,help_text='please upload svg icon')
    details = RichTextUploadingField(null=True,blank=True,help_text="try not to put very large text")
 
    def __str__(self):
        return str(self.title) 

    def image_tag(self):
        if self.icon != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.icon))

class Design_engineering(models.Model):
    title = models.CharField(max_length=255,help_text='title must be in 255 character')
    icon =models.FileField(upload_to="design_engineering",null=True,blank=True,help_text='please upload svg icon')
    details = RichTextUploadingField(null=True,blank=True,help_text="try not to put very large text")
 
    def __str__(self):
        return str(self.title) 

    def image_tag(self):
        if self.icon != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.icon))

class Project_management(models.Model):
    title = models.CharField(max_length=255,help_text='title must be in 255 character')
    icon =models.FileField(upload_to="project_management",null=True,blank=True,help_text='please upload svg icon')
    details = RichTextUploadingField(null=True,blank=True,help_text="try not to put very large text")
 
    def __str__(self):
        return str(self.title) 

    def image_tag(self):
        if self.icon != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.icon))

class Product(models.Model):
    name = models.CharField(max_length=255,help_text='title must be in 255 character')
    product_url =models.URLField(null=True,blank=True)
    image =models.ImageField(upload_to="product_image",null=True,blank=True)
    details = RichTextUploadingField(null=True,blank=True,help_text="try not to put very large text")

    def image_tag(self):
        if self.image != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.image))

class Contact(models.Model):
    name = models.CharField(max_length=255,null=True,blank=True)
    phone = models.CharField(max_length=255,null=True,blank=True)
    email =models.EmailField(null=True,blank=True)
    message =models.TextField(null=True,blank=True)
    file = models.FileField(upload_to='documents/',blank=True)
    position = models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return str(self.name)

projectapp/models.py
from django.db import models
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.html import mark_safe
from django.conf import settings


# CATEGORY_CHOICES = (
# ("LN", "Landmark"),
# ("RN", "Running"),
# ("UP", "Upcoming"),
# ("CO", "Complated"),)
         
# # Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name) 
    
    def get_absolute_url(self):
        return reverse('homeapp:categorypage', kwargs={'pk':self.pk})
    

class Project(models.Model):
    title = models.CharField(max_length=255,help_text='title must be in 255 character')
    categories = models.ForeignKey(Category,on_delete=models.CASCADE,null=True,blank=True)
    thumnail_image =models.ImageField(upload_to="project_imgs",help_text='upload thumnail image for project')
    details = RichTextUploadingField(null=True,blank=True,help_text="write details about your project")
    services = RichTextUploadingField(null=True,blank=True,help_text="write service of your project as a list")
    location = models.TextField(null=True,blank=True,help_text="write loaction about your project")
    contractors = models.TextField(null=True,blank=True,help_text="write contractors about your project")
    developer = models.TextField(null=True,blank=True,help_text="write developer about your project")

    def __str__(self):
        return str(self.title) 

    def image_tag(self):
        if self.thumnail_image != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.thumnail_image))


class ProjectImages(models.Model):
    case = models.ForeignKey(Project,on_delete=models.CASCADE,null=True,blank=True)
    images = models.ImageField(upload_to="file_upload", null = True, blank = True,help_text='upload images for project')



class Scope(models.Model):
    title =  models.CharField(max_length=255,help_text='title must be in 255 character')
    icon =models.FileField(upload_to="Scope_images",null=True,blank=True,help_text='please upload svg icon')
    short_description = models.TextField(null=True,blank=True,help_text="write a very short details about your project")
    long_text = RichTextUploadingField(null=True,blank=True,help_text="write long details about your project")

    def __str__(self):
        return str(self.title) 

    def image_tag(self):
        if self.icon != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.icon))
 

homeapp/views.py
from django.shortcuts import render
from projectapp.models import Scope,Project,Category
from .models import Consultancy,Design_engineering,Product,Contact

def home(request):
    scopes = Scope.objects.all().order_by('-id')[:6]
    projects = Project.objects.all()[:6]

    consultancys = Consultancy.objects.all()[:6]
    design_engineerings = Design_engineering.objects.all()[:6]
    # project_managements = Project_management.objects.all()[:6]

    context={
        'scopes':scopes,
        'projects':projects,
        'consultancys':consultancys,
        # 'project_managements':project_managements,
        'design_engineerings':design_engineerings
    }
    return render(request,'homeapp/homepage.html',context)

def category_filter(request,pk):
    category = Project.objects.filter(categories=pk)
    cat_name =Category.objects.filter(pk=pk).first()
    context={
        'category': category,
        'cat_name':cat_name
    }
    return render(request,'homeapp/category.html',context )


def product(request):
    products =Product.objects.all()
    projects = Project.objects.all()[:6]
    context={
        'products': products,
        'projects':projects
    }
    return render(request,'homeapp/product.html',context) 

def product_details(request,pk):
    object = Product.objects.get(pk=pk)
    all = Product.objects.all()
    context ={
        'object':object,
        'all':all
    }
    return render(request,'homeapp/product_details.html',context)

def who_we_are(request):
    return render(request,'homeapp/who_we_are.html') 

def who_we_are_for(request):
    return render(request,'homeapp/who_we_are_for.html')

def career(request):
    # if request.method =="POST" and request.FILES['file']:
    if request.method == 'POST' and request.FILES.get('file', False):
        name = request.POST.get('name')
        phone =request.POST.get('phone')
        email = request.POST.get('email')
        message = request.POST.get('message')
        position = request.POST.get('position')
        file = request.FILES['file']
        Contact.objects.create(name=name,email=email,message=message,phone=phone,position=position,file=file)
        return render(request,'global/thankyou.html')
    
    return render(request,'global/career.html')

templates/global/career.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Booking Form HTML Template</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<style> 

.section {
	position: relative;
	height: 100vh
}

.section .section-center {
	position: absolute;
	top: 50%;
	left: 0;
	right: 0;
	-webkit-transform: translateY(-50%);
	transform: translateY(-50%)
}

.booking {
	font-family: montserrat, sans-serif;
	background-image: url(img/background.jpg);
	background-size: cover;
	background-position: center
}

.booking::before {
	content: '';
	position: absolute;
	left: 0;
	right: 0;
	bottom: 0;
	top: 0;
	background: rgba(47, 103, 177, .6)
}

.booking-form {
	background-color: #fff;
	padding: 50px 20px;
	-webkit-box-shadow: 0 5px 20px -5px rgba(0, 0, 0, .3);
	box-shadow: 0 5px 20px -5px rgba(0, 0, 0, .3);
	border-radius: 4px
}

.booking-form .form-group {
	position: relative;
	{% comment %} margin-bottom: 30px {% endcomment %}
    margin-bottom: 15px;
}

.booking-form .form-control {
	background-color: #ebecee;
	border-radius: 4px;
	border: none;
	height: 40px;
	-webkit-box-shadow: none;
	box-shadow: none;
	color: #3e485c;
	font-size: 14px
}

.booking-form .form-control::-webkit-input-placeholder {
	color: rgba(62, 72, 92, .3)
}

.booking-form .form-control:-ms-input-placeholder {
	color: rgba(62, 72, 92, .3)
}

.booking-form .form-control::placeholder {
	color: rgba(62, 72, 92, .3)
}

.booking-form input[type=date].form-control:invalid {
	color: rgba(62, 72, 92, .3)
}

.booking-form select.form-control {
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none
}

.booking-form select.form-control+.select-arrow {
	position: absolute;
	right: 0;
	bottom: 4px;
	width: 32px;
	line-height: 32px;
	height: 32px;
	text-align: center;
	pointer-events: none;
	color: rgba(62, 72, 92, .3);
	font-size: 14px
}

.booking-form select.form-control+.select-arrow:after {
	content: '\279C';
	display: block;
	-webkit-transform: rotate(90deg);
	transform: rotate(90deg)
}

.booking-form .form-label {
	display: inline-block;
	color: #3e485c;
	font-weight: 700;
	margin-bottom: 6px;
	margin-left: 7px
}

.booking-form .submit-btn {
	display: inline-block;
	color: #fff;
	background-color: #1e62d8;
	font-weight: 700;
	padding: 14px 30px;
	border-radius: 4px;
	border: none;
	-webkit-transition: .2s all;
	transition: .2s all
}

.booking-form .submit-btn:hover,
.booking-form .submit-btn:focus {
	opacity: .9
}

.booking-cta {
	{% comment %} margin-top: 80px; {% endcomment %}
    margin-top: 250px;
	margin-bottom: 30px
}

.booking-cta h1 {
	font-size: 52px;
	text-transform: uppercase;
	color: #fff;
	font-weight: 700
}

.booking-cta p {
	font-size: 16px;
	color: rgba(255, 255, 255, .8)
}


</style>

<body>
<div id="booking" class=" booking section">
    <div class="section-center">
        <div class="container">
            <div class="row">
                <div class="col-md-7 col-md-push-5">
                    <div class="booking-cta">
                        <h1>REAL ESTATE EXPERT? | JOIN THE TEAM | APPLY NOW!</h1>
                        <p>Fill out the form  submit your resume and one of our hiring managers will contact you if we have an available position that matches your resume.
                        </p>
                    </div>
                    <div class="form-btn">
                        <button class="submit-btn"><a href="{% url 'homeapp:homepage' %}">Back to Homepage</a></button>
                    </div>
                </div>
                <div class="col-md-4 col-md-pull-7">
                    <div class="booking-form">

                        <form method="POST" enctype="multipart/form-data">
                           {% csrf_token %}
                            <div class="form-group">
                                <span class="form-label">Your Name</span>
                                <input name="name" class="form-control" type="text" placeholder="Enter your phone name">
                            </div>
                            <div class="form-group">
                                <span class="form-label">Your Email</span>
                                <input name="email" class="form-control" type="text" placeholder="Enter your phone email">
                            </div>
                            <div class="form-group">
                                <span class="form-label">Your Phone</span>
                                <input name="phone" class="form-control" type="text" placeholder="Enter your phone number">
                            </div>

                            <div class="form-group">
                                <span class="form-label">Your Position</span>
                                <input name="position" class="form-control" type="text" placeholder="Enter your position number">
                            </div>

                            <div class="form-group">
                                <span class="form-label">Upload your CV:</span>
                                <input  class="form-control" type="file" name="file">
                              </div>

                            <div class="form-group">
                                <span class="form-label">Your Message</span>
                                <input name="message" class="form-control" style="height:120px;" type="text" placeholder="Enter your message">
                            </div>
                          
                            <div class="form-btn">
                                <button class="submit-btn">Check availability</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"6ed413e73af878c4","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}' crossorigin="anonymous"></script>
</body>
</html>

templates/global/navbar.html
{% load static %}
{% block content %}


<div data-collapse="medium" data-animation="default" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="nav-bar-projects black w-nav">
    <div class="container-2 w-container">
        <a href="{% url 'homeapp:homepage' %}" aria-current="page" class="brand-2 w-nav-brand w--current">
            <img src="{% static 'images/logo.jpeg' %}" style="height: 80px; width: 300px;"  alt="Building Envelope Systems Dubai official logo" class="image-2"/></a>
        <nav role="navigation" class="nav-menu w-nav-menu">
            <div style="margin-right:30px;">
              <a class="">
                <img src="{% static 'images/facebookicon.png' %}"
                 style="color:#E4405F;font-size:25px;padding:6px;height:40px;width:40px;margin-right:1px; margin-left:1px;" alt="facebook">
                {% comment %} <i style="color:#1877F2;font-size:25px;padding:6px;height:30px;width:30px;margin-right:6px; margin-left:6px;"  class="fa-brands fa-facebook"></i> {% endcomment %}
              </a> 
              <a class="">
                <img src="{% static 'images/instragramicon.png' %}" style="color:#E4405F;font-size:25px;padding:6px;height:40px;width:40px;margin-right:1px; margin-left:1px;" alt="instagram">
                
              </a>
              <a class="" href="https://wa.me/+01982600163?text=Wellcome to live whatsapp chat">
                <img src="{% static 'images/whatsupicon.png' %}" style="color:#E4405F;font-size:25px;padding:6px;height:40px;width:40px;margin-right:1px; margin-left:1px;" alt="whatsapp">
              </a>  

              <span style=" color:rgb(255, 255, 255);">01982600163</span>
            </div>
             

            <div data-delay="0" data-hover="true" class="w-dropdown">
                <div class="nav-button-dropdown w-dropdown-toggle">
                    <div class="w-icon-dropdown-toggle"></div>
                    <div>About</div>
                </div>
                <nav class="dropdown-list w-dropdown-list">
                    <a href="{% url 'homeapp:who_we_are_page' %}" class="drop-link black w-dropdown-link">Who we are</a>
                    <a href="{% url 'homeapp:who_we_are_for_page' %}" class="drop-link black w-dropdown-link">Who we&#x27;re for </a>
                </nav>
            </div>
            <div data-delay="0" data-hover="true" class="w-dropdown">
                <div class="nav-button-dropdown w-dropdown-toggle">
                    <div class="w-icon-dropdown-toggle"></div>
                    <div>Services</div>
                </div>
                <nav class="dropdown-list w-dropdown-list"><a href="/#consultancy" class="drop-link black w-dropdown-link">Consultancy</a>
                    <a href="/#design" class="drop-link black w-dropdown-link">Design + Engineering</a>
                    <a href="/#management" class="drop-link black w-dropdown-link">Project Management</a>
                    <a href="/#scope" class="drop-link black w-dropdown-link">Scope</a>
                </nav>
            </div>
            
            <!--<div data-delay="0" data-hover="true" class="w-dropdown">-->
            <!--    <div class="nav-button-dropdown w-dropdown-toggle">-->
            <!--        <div class="w-icon-dropdown-toggle"></div>-->
            <!--        <div>Products</div>-->
            <!--    </div>-->
            <!--    <nav class="dropdown-list w-dropdown-list">-->
            <!--        <a href="minimal-sliding-windows-doors.html" class="drop-link w-dropdown-link">Minimal Sliding Windows and Doors</a>-->
            <!--        <a href="minimal-pivot-windows-doors.html" class="drop-link w-dropdown-link">Minimal Pivot Windows and Doors</a>-->
            <!--        <a href="guillotine-automatic-multi-leaf-vertical-sliding-windows-doors.html" class="drop-link w-dropdown-link">Guillotine Windows and Doors</a>-->
            <!--    </nav>-->
            <!--</div>-->
            
            {% comment %} <a href="/#projects" class="new-nav-button w-nav-link">Projects</a> {% endcomment %}
          

            <div data-delay="0" data-hover="true" class="w-dropdown">
                <div class="nav-button-dropdown w-dropdown-toggle">
                    <div class="w-icon-dropdown-toggle"></div>
                    <div>Projects</div>
                </div>
                <nav class="dropdown-list w-dropdown-list">
                    {% for cat in categories %}
                    
                    <a href="{{cat.get_absolute_url}}" class="drop-link black w-dropdown-link">{{cat.name}}</a>
                    {% endfor %}
                </nav>
            </div>


            <a href="{% url 'homeapp:product_page' %}" class="new-nav-button w-nav-link">Product</a>
            <a href="{% url 'homeapp:career_page' %}" class="new-nav-button w-nav-link">Career</a>
            <a href="/#contact" class="new-nav-button w-nav-link">Contact</a>
        </nav>
        <div class="menu-button w-nav-button">
            <div class="icon wide home w-icon-nav-menu"></div>
        </div>
    </div>
</div>
<div data-animation="default" class="navbar-3 w-nav" data-easing2="ease" data-easing="ease" data-collapse="small"
 >
    <div class="container-2 w-container">
        <a href="{% url 'homeapp:homepage' %}" aria-current="page" class="brand-2 w-nav-brand w--current">
            <img src="{% static 'images/logo.jpeg' %}" style="height: 80px; width: 300px;"  alt="Building Envelope Systems logo" class="image-2"/></a>
        <nav role="navigation" class="nav-menu w-nav-menu">
            <div data-delay="0" data-hover="false" class="w-dropdown">
                <div class="nav-button-dropdown mobile w-dropdown-toggle">
                    <div class="w-icon-dropdown-toggle"></div>
                    <div>About</div>
                </div>
                <nav class="dropdown-list w-dropdown-list"><a href="/#about1" class="drop-link w-dropdown-link">Who we are</a><a href="#about2" class="drop-link w-dropdown-link">Who we&#x27;re for </a></nav>
            </div>
            <div data-delay="0" data-hover="false" class="w-dropdown">
                <div class="nav-button-dropdown mobile w-dropdown-toggle">
                    <div class="w-icon-dropdown-toggle"></div>
                    <div>Services</div>
                </div>
                <nav class="dropdown-list w-dropdown-list"><a href="#consultancy" class="drop-link w-dropdown-link">Consultancy</a><a href="#design" class="drop-link w-dropdown-link">Design + Engineering</a><a href="#management" class="drop-link w-dropdown-link">Project Management</a><a href="#scope" class="drop-link w-dropdown-link">Scope</a></nav>
            </div>
            <div data-delay="0" data-hover="false" class="dropdown-2 w-dropdown">
                <div class="nav-button-dropdown mobile w-dropdown-toggle">
                    <div class="w-icon-dropdown-toggle"></div>
                    <div>Products</div>
                </div>
                <nav class="dropdown-list w-dropdown-list"><a href="minimal-sliding-windows-doors.html" class="drop-link w-dropdown-link">Minimal Sliding Windows and Doors</a><a href="minimal-pivot-windows-doors.html" class="drop-link w-dropdown-link">Minimal Pivot Windows and Doors</a><a href="guillotine-automatic-multi-leaf-vertical-sliding-windows-doors.html" class="drop-link w-dropdown-link">Guillotine Windows and Doors</a></nav>
            </div>
            <a href="#projects" class="new-nav-button w-nav-link">Projects</a><a href="#news" class="new-nav-button w-nav-link">News</a>
            <a href="#contact" class="new-nav-button w-nav-link">Contact</a>

            <a class="">
                <img src="{% static 'images/facebookicon.png' %}"
                 style="color:#E4405F;font-size:25px;padding:6px;height:40px;width:40px;margin-right:1px; margin-left:1px;" alt="facebook">
                {% comment %} <i style="color:#1877F2;font-size:25px;padding:6px;height:30px;width:30px;margin-right:6px; margin-left:6px;"  class="fa-brands fa-facebook"></i> {% endcomment %}
              </a> 
              <a class="">
                <img src="{% static 'images/instragramicon.png' %}" style="color:#E4405F;font-size:25px;padding:6px;height:40px;width:40px;margin-right:1px; margin-left:1px;" alt="instagram">
                
              </a>
              <a class="" href="https://wa.me/+01982600163?text=Wellcome to live whatsapp chat">
                <img src="{% static 'images/whatsupicon.png' %}" style="color:#E4405F;font-size:25px;padding:6px;height:40px;width:40px;margin-right:1px; margin-left:1px;" alt="whatsapp">
              </a>  
             
{% comment %}             
            
            
            <a style="background-color:#fff;" class="new-nav-button w-nav-link">
                    <img style="color:#fff;" src="{% static 'images/whatsapp.png' %}">
                    <span style="color:black;">01982600163</span>
                </a> {% endcomment %}
        </nav>
        <div class="menu-button w-nav-button">
            <div class="icon w-icon-nav-menu"></div>
        </div>
    </div>
</div>



{% endblock %}

templates/homeapp/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



<div class="scope-header wf-section" style="background-color:#11a5ff !important;">
    <div class="container-10 w-container">
        <div class="scope-header-div">
            <h1 class="heading-2 scope">{{object.name}}</h1>
        </div>
    </div>
</div>
<!-- 
<div class="scope-header wf-section"> -->
    <div class="container-10 w-container">

 <img src="{{object.image.url}}" alt="img" style="padding-top:15px !important; height:450px;">
  
</div>
     
<!-- 
    </div> -->


<div id="projects" class="section _200 wf-section" style="padding-top:15px !important;">
    <div class="w-dyn-list">
        <div role="list" class="w-dyn-items">
            <div role="listitem" class="w-dyn-item">
                <div class="w-container">

            
                   
                   <p class="paragraph-70 project">{{object.details|safe}}</p>

                   <button style="padding:10px;background-color:#11a5ff;
                   padding-left:50px;padding-right:50px; width:100%;"> 
                       <a style="text-decoration: none; color:white"  href="https://wa.me/+01982600163?text=Wellcome to live whatsapp chat" style="color:white;"> Buy Now </a></button>


                    <div data-w-id="bce33b4f-3f1d-5ca9-a085-2ca327c5dc5e" style="opacity:1" class="project-columns w-row">
                       {% for p in object.projectimages_set.all %}
					   <div class="column-7 w-col w-col-6">
                            <div style="background-image:url({{p.images.url}})" class="div-block-10"></div>
                        </div>
						{% endfor %}
						
                    </div>
					
                    {% comment %} <div data-w-id="385b4403-681b-06dd-e3dc-b0b9d0e50739" style="opacity:0" class="project-columns portrait w-row">
                        <div class="column-9 w-col w-col-4">
                            <div style="background-image:url({{object.thumnail_image.url}})-23b.jpg&quot;)" class="div-block-11"></div>
                        </div>
                        <div class="column-10 w-col w-col-4">
                            <div style="background-image:url(_https_/uploads-ssl.webflow.com/5ccaa276b7202a16f52b1381/5cd155922a542ffe0ba30677_92001-RPT-C144200-DG-000029(1.html)-20.jpg&quot;)" class="div-block-11"></div>
                        </div>
                        <div class="column-11 w-col w-col-4">
                            <div style="background-image:url(_https_/uploads-ssl.webflow.com/5ccaa276b7202a16f52b1381/5cd159692a542f96a9a30d9e_92001-RPT-C144200-DG-000029(1)-22b.jpg&quot;)" class="div-block-11"></div>
                        </div>
                    </div>
					
                    <div class="image-copyright w-condition-invisible w-dyn-bind-empty"></div>  {% endcomment %}


                </div>
            </div>
        </div>
    </div>



  
    <div class="container-9 w-container">
        <h3 data-w-id="e2eb9168-b021-aba7-ba86-bdbaf881c7d8" style="opacity:1" class="subhead">More projects:</h3>
        <div data-w-id="2d0e94ff-8826-bcdd-2e25-b84de2c3d495" style="opacity:1" class="w-dyn-list">
            <div role="list" class="collection-list-5 w-dyn-items">

         


                {% for product in  all %}
                <div data-w-id="3da58f03-fdd8-3628-a5d2-ef6d4fe7bc7e" style="opacity:0; margin-bottom:10px;" role="listitem" class="collection-item-2 _3 w-dyn-item">
                    <div class="grey-div">
                        <div data-w-id="22e1163c-45b4-b1b5-fe81-7e30a284207b" style="background-image:url({{product.image.url}});opacity:0" class="div-block-12">
                            <div data-w-id="2d441236-0d1c-255c-10c5-af4e1e5a25b3" style="opacity:0" class="location-div">
                                <div class="location-test home">{{product.name}}</div>
                            </div>
                        </div>
                        <div class="service-div line news">
                            <h3 class="heading-7">{{product.name}}</h3>
                            {% comment %} <p data-w-id="d4a9fea8-e767-b6eb-0060-bd09afebcd3f" style="opacity:0" class="news-para">{{project.details|safe|truncatechars:200}}.</p> {% endcomment %}
                            <a  href="{% url 'homeapp:product_detailspage' product.pk %}" class="project-button w-button">View project →</a>
                        </div>
                    </div>
                </div>
                {% endfor %}




            </div>
        </div>
    </div>



</div>



{% endblock %}